name: Ubuntu Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-setuptools python3-pip libcanberra-dev libdbus-glib-1-dev libglib2.0-dev libgtk2.0-dev libluajit-5.1-dev libnotify-dev libpci-dev libperl-dev libproxy-dev libssl-dev python3-dev python3-cffi mono-devel desktop-file-utils
          sudo pip3 install meson

      - name: Configure
        run: meson build -Dtext=true -Dtheme-manager=true -Dauto_features=enabled

      - name: Build
        run: ninja -C build

      - name: Test
        run: ninja -C build test

      - name: Install
        run: sudo ninja -C build install
